global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: 'application'
    scrape_interval: 30s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['internshiptaskone_app_1:2020']


rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]