global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]


rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]